vegastrike/Vega-Strike-Engine-Source

src/cmd/unit_generic.cpp

The proposed changes fix the reload mechanism for mounted guns. Currently most vessels cannot be reloaded. Some vessels that can reload their mounted gun slots do so in an inconsistent manner. I made a lengthy post in the vegastrike forum which contains screenshot and a detailed explanation why I think that the reload mechanism was intended to work this way.

Fix reloading of guns independently of mount volume.

---

engine/src/vs_math.h

Convert to using the provided versions of the functions via the standard library as of C++11.
Hopefully this will fix the build error on Ubuntu 16.04 too.

Enhancement: std::(isfinite, isnan)

---

engine/src/savegame.cpp

Fixes #85 -- will likely need to use something else than vs_dprintf(), but I'll leave that to people with more C++ fu.
Looks like this fix was never merged in from the VS-taose codebase, yet its commit message is present in the ChangeLog?  What's that all about?

Try to make savegame memory allocation slightly more robust

---

engine/src/cmd/basecomputer.cpp

In Priv:WCU, it is very convenient to be able to check the name and type
of the current base when trading via the base computer, since the
computer tracks the prices seen at other in-system bases.

Add base name and type to base computer header

---

.travis.yml

Removed Ubuntu 14.04 LTS from Travis-CI, thus officially dropping support of **compilation** on that distro.
Currently this PR is a preparation/offer and will be merged after finishing the [vote on the matter](https://github.com/vegastrike/Vega-Strike-Engine-Source/issues/40#issuecomment-623743970)
@vegastrike/core-reviewers

Removed support of Ubuntu 14.04 LTS

---

README.md
engine/CMakeLists.txt
sh/vsbuild.sh

Older versions of Ubuntu and its derivates have an issue where the
`file` utility will interpret Position Independent Executables as
shared libraries:
https://bugs.launchpad.net/ubuntu/+source/file/+bug/1747711
As a workaround, allow setting the option `ENABLE_PIE`
(defaults to `OFF`) and add a suitable message for maintainers in both
the CMake code, during configuration runs and in ccmake.
Update the build instructions in `README.md` to reflect this change.
Additionally, switch sh/vsbuild.sh to the Debug target (see #50) and enable verbose compilation by default to make it easier to spot errors in CI.
Closes #94

Set -fno-PIE by default as a Ubuntu/Mint workaround

---

README.md
sh/vsbuild.sh

Older versions of CMake (used on older Ubuntu LTS versions) don't
support the `-j` parameter.

Switch back from `cmake --build` to `make` for builds

---

CONTRIBUTING.rst

First draft of the Vega Strike Core Engine specific Contributing guidelines. This should provide an online us going forward.
I did reference the original guidelines at https://wiki.vega-strike.org/HowTo:Contribute. I wanted this to be a bit more targeted at the Core Engine work in this repository. Similarly we can add an asset specific one to the Asset Masters repository.
Closes #27
Related: https://github.com/vegastrike/Assets-Masters/issues/3

Contributor Guidelines: First draft

---

.gitignore
engine/CMakeLists.txt
engine/src/cmd/ai/firekeyboard.cpp
engine/src/lin_time.cpp
engine/src/main_loop.cpp

Code Changes:
Issues:
Closes #28 
Purpose:
- What is this pull request trying to do? **Make it so that users can pause and resume the game freely, without crashes.**
- What release is this for? **0.6.0**
- Is there a project or milestone we should apply this to? **0.6.x**

Fix resume crash on 0.6.x

---

engine/src/posh.h

Previously, almost all non-x86 architectures were treated as big endian by the `posh` abstraction layer. This is incorrect for ppc64le, which is a little endian architecture. This PR causes vegastrike to correctly treat ppc64le as little endian, avoiding incorrect byte swaps to correct endianness.
I think other architectures such as aarch64 might be affected as well, but I'm not an expert on those.
(This posh layer seems very arcane.. we should consider switching to a more modern abstraction layer in the long term, some of the things it does are covered by recent versions of the C++ standard such as data types of guaranteed length)
Code Changes:
Issues:
- Resolves #160
Purpose:
- What is this pull request trying to do? See above
- What release is this for? I would consider this a hotfix, …

Treat ppc64le as little endian architecture. Fix #160

---

.travis.yml

As I understand from the documentation the workflow is as follows (after merging this PR):
1. Through Github we create a new release
2. Github creates a tag on the branch
3. Travis CI picks up the tag and creates a new build
4. Upon success, Travis CI pushes the packages into the release created in step 1
TODO:

Enable Release CD on 0.6.x

---

engine/CMakeLists.txt

In #202, the following change was made:
```diff
ELSEIF (USE_PYTHON_3)
-            SET(BOOST_PYTHON_COMPONENT "python3")
+            SET(BOOST_PYTHON_COMPONENT "python-py${PYTHON_VERSION_MAJOR}${PYTHON_VERSION_MINOR}")   # This may be specific to Ubuntu xenial
```
Whilst this works fine for Debian and Debian-based distros (e.g. Ubuntu, Mint) - at least those that still use a version of `Boost` below `1.67` - this will have broken `python 3` builds for most, if not all, distros that are *not* based on Debian (and are *also* running a `Boost` version lower than `1.67`).
The attached changeset resolves this, putting in a specific conditional for the one distro (Xenial) that actually needs the `boost-python` specifying in such a manner for the `python 3` build to work, and restoring the old …

Correct boost_python3 component on non-Debian systems

---

engine/src/cmd/basecomputer.cpp

Code Changes:
Issues:
**Fixes #168 .
Fixes #216 .**
Purpose:
- What is this pull request trying to do? **Use best practices for memory safety when formatting strings.**
- What release is this for? **0.7.x?**
- Is there a project or milestone we should apply this to? **@BenjamenMeyer ?**

In basecomputer.cpp, convert all instances of sprintf to use boost::format instead

---

engine/src/gldrv/gl_texture.cpp

Code Changes:
Issues:
Issue #256 
Purpose:
This PR removes an pre-processor ifdef that is causing the compiler warning. One can safely assume that every OpenGL driver running today supports this. 
Any.
Nope.

Fixes a compile error by removing an out of date ifdef

---

engine/src/cmd/base_interface.cpp

Code Changes:
Issues:
Looks like a copy/paste bug.
The intended comaprizon was probably against the `bas' variable.
Purpose:
Fix a warning
Next one
Next one

Fix tautological comparizon warning

---

engine/CMakeLists.txt
engine/objconv/CMakeLists.txt
engine/objconv/mesher/CMakeLists.txt
engine/setup/CMakeLists.txt

and make associated changes to each CMakeLists.txt file
Code Changes:
Issues:
**Resolves #266** 
Purpose:
- What is this pull request trying to do? **Rename the CMake project to avoid confusion between "Vega Strike" (the game engine); VSU (the fictional Vega Strike Universe); and UtCS (Upon the Coldest Sea, a particular game built using the Vega Strike game engine, and set in the VSU).**
- What release is this for? **0.7.x**
- Is there a project or milestone we should apply this to? **0.7.x, and possibly 0.6.x as well, though that would be a separate pull request**

Rename entire CMake project from 'vsUTCS' to 'Vega_Strike'

---

.travis.yml

CI changes only, to increase coverage. Shouldn't affect functionality in any way.

Add Ubuntu 20.04 Focal support to Travis-CI

---

engine/CMakeLists.txt
engine/src/cmd/asteroid_generic.cpp
engine/src/cmd/asteroid_generic.h
engine/src/cmd/collision.cpp
engine/src/cmd/collision.h
engine/src/cmd/enhancement_generic.h
engine/src/cmd/missile.h
engine/src/cmd/missile_generic.cpp
engine/src/cmd/missile_generic.h
engine/src/cmd/movable.cpp
engine/src/cmd/nebula_generic.cpp
engine/src/cmd/nebula_generic.h
engine/src/cmd/planet.cpp
engine/src/cmd/planet.h
engine/src/cmd/planet_generic.h
engine/src/cmd/unit_collide.cpp
engine/src/cmd/unit_generic.cpp
engine/src/cmd/unit_generic.h
engine/src/cmd/unit_type.h
engine/src/game_config.h
engine/src/gfx/tvector.h

Purpose:
- What is this pull request trying to do? This is the refactoring of the reactToCollision functions throughout the unit class hierarchy. I've extracted the code and centralized it in a separate class. While it is still impossible to write unit tests for it, a second refactor will enable that too.  
- What release is this for? 0.7
- Is there a project or milestone we should apply this to? 0.7
Issues:
- Collision between units still isn't good, though better than before IMO. Units typically explode on impact.
Code Changes:
- [No ] Have the PR Validation Tests been run? See https://github.com/vegastrike/Vega-Strike-Engine-Source/wiki/Pull-Request-Validation

Move reactToCollision code to its own class

---

engine/src/cmd/pilot.cpp
engine/src/cmd/unit_util_generic.cpp

Code Changes:
Issues:
**Closes #351** 
Purpose:
- What is this pull request trying to do? **Fix a segfault that occurs after the player dies, on the "Grim Reaper" screen**
- What release is this for? **0.8.x, probably**
- Is there a project or milestone we should apply this to? **0.8.x, probably**

fix segfault post player death by checking for null unit in getAnger etc

---

.travis.yml
Dockerfile
engine/CMakeLists.txt

Code Changes:
Issues:
**#362** 
Purpose:
- What is this pull request trying to do? **Retire the Python 2 builds, which we no longer officially support as of 0.8.x**
- What release is this for? **0.8.x**
- Is there a project or milestone we should apply this to? **0.8.x**

Retire py2 builds

---

engine/CMakeLists.txt

Code Changes:
Issues:
Fixes #391 
Purpose:
- What is this pull request trying to do? Fix a missing boost dependency for the .deb installer for Vega Strike v0.7.0 beta py3 on Ubuntu bionic

CPack: Add libboost-date-time1.58.0 as apt dependency for Ubuntu bionic

---

doc/man/vegastrike.1

Revisited the man page, cleaning up the formatting and updating
content.
Code Changes:
Issues:
- #96 - updating related information in the man page
- vegastrike/infrastructure-tracking/issues/6
Purpose:
Update the man page with more relevant and recent information. Clean up the formatting.

Enhancement: Updating the manpage

---

engine/src/vsfilesystem.cpp

Code Changes:
Issues:
#389
Purpose:
This PR allows the hard-coded galaxy name (`universe/milky_way.xml`) to be overridden by settings in `vegastrike.config`.

Read galaxy XML file name from vegastrike.config

---

script/package

Code Changes:
Issues:
- #391 
Purpose:
Fixes the `script/package` for the new location of the mesh and settings tools

Bug Fix: script/package - binary locations (0.7.x)

---

script/package

There's a circular relationship between CMake and the dependency.list
file such that CMake has to be run first to build the binaries,
then script/package to build the dependencies, but then CMake has
to be run again for CPack to pick up the dependency list for the
packages to be correct as intended.
Code Changes:
Issues:
- #391
Purpose:
- Make the build system re-run cmake after building the dependencies so it picks up the right ones
- Synchronizes and additional change from #424 to 0.7.x
NOTE: This alleviates the issues external to the CMake configuration itself.

Bug Fix: run cmake before packaging

---

engine/CMakeLists.txt

First level quoting is used for cmake,
second level is consumed by the shell executing the compiler,
so there needs to be a third level for the `DATA_DIR` macro to be recognized as a string inside the source files.
Without this patch currently it will get transformed like this:
```
cmake: "${DEFINES} -DDATA_DIR=\"${DATADIR}\""
calls gcc:
gcc ... -DDATA_DIR="/foo/bar"
defines:
#define DATA_DIR /foo/bar
```
So the DATA_DIR is no longer a string.

cmake: Fix DATA_DIR quoting

---

engine/src/posh.h

This is a patch from the openSUSE games repository to enable Aarch64 support.

posh.h add Aarch64 support

---

engine/src/cmd/basecomputer.cpp
engine/src/cmd/script/director_generic.cpp
engine/src/savegame.cpp
engine/src/savegame.h

Code Changes:
Issues:
- #149
Purpose:
- What is this pull request trying to do?  **Preventing crashes from loading non-utf8 saved games via pre-emptive checks, alerting the user when it happens. Serving as a place for discussion of the issue, whatever direction the changes will go.**
- What release is this for?  **0.8.x, 0.9.x**
- Is there a project or milestone we should apply this to?  **0.8.x, 0.9.x**

Utf-8 check, C++ initial version

---

engine/src/cmd/basecomputer.cpp

Code Changes:
Issues:
- #149 
Purpose:
- What is this pull request trying to do?  **Skipping the utf-check for the New_Game special case as it's not a real file; it makes the Campaign (main menu) and New (while docked in game) buttons work properly**
- What release is this for?  **0.8.x**
- Is there a project or milestone we should apply this to?  **0.8.x**

Don't utf8-check New_Game

---

engine/src/cmd/basecomputer.cpp

Code Changes:
Issues:
- #149, #470
Purpose:
Backport #470 to 0.8.x - a slight tweak of #463 to prevent overlaps with the in-game constant saved game name of `New Game`
Thanks @P-D-E for the work!
Test Details:
- Test 1: Start game; select Load, select an invalid UTF-8 saved game; click load.
- Test 2: Start game; start a new campaign; go to the concourse; click save/load; select an invalid UTF-8 saved game; click load
In both cases it should fail to load the game and present a message to the user.

Backport 470 0.8.x

---

.github/workflows/Windows-CI.yml

Code Changes:
Issues:
Purpose:
- What is this pull request trying to do? Optimize build times for Windows CI (Continuous Integration) by caching the vcpkg dependencies
- What release is this for? 0.9.x; can probably be backported to 0.8.x as well
- Is there a project or milestone we should apply this to? 0.8.x, 0.9.x

Windows CI: Add dependency caching

---

.github/workflows/macos-ci.yml
engine/CMakeLists.txt
script/cibuild

This PR provides a workflow for a MacOS CI. For now it must be manually activated, however [here is a recent run](https://github.com/s0600204/Vega-Strike-Engine-Source/actions/runs/929734201) to give some idea of what the end result is.
As mentioned in the related issue (#78), both `OpenAL` and `OpenGL` (or at least the Apple-provided implementations of them) are now considered deprecated on MacOS. Thus the workflow file, along with testing building with both `clang` and `gcc`, also provide jobs that attempt to use alternate `OpenAL` and `OpenGL` implementations (`OpenAL-soft` and `Mesa3D`/`freeGLUT` respectively).
The PR does not contain any attempted fixes for building on MacOS, other than that needed to facilitate using `OpenAL-soft`, `Mesa3D`, and `freeGLUT`. (For those, see the below …

MacOS CI Workflow File

---

.dockerignore
.gitignore
Dockerfile
engine/CMakeLists.txt
script/bootstrap

Code Changes:
- [In progress] Have the PR Validation Tests been run? See https://github.com/vegastrike/Vega-Strike-Engine-Source/wiki/Pull-Request-Validation
Issues:
- Closes #364 
Purpose:
- What is this pull request trying to do? Get rid of the no-longer-needed Python2 stuff from 0.9.x and following

No More Python 2

---

engine/CMakeLists.txt
engine/src/cmd/armed.cpp
engine/src/cmd/collision.cpp
engine/src/cmd/computer.cpp
engine/src/cmd/damageable.cpp
engine/src/cmd/energetic.cpp
engine/src/cmd/missile.cpp
engine/src/cmd/movable.cpp
engine/src/cmd/planet.cpp
engine/src/cmd/unit_generic.cpp
engine/src/cmd/unit_generic.h
engine/src/configuration/configuration.cpp
engine/src/configuration/configuration.h
engine/src/configuration/game_config.cpp
engine/src/configuration/game_config.h
engine/src/configuration/tests/configuration_tests.cpp
engine/src/configuration/tests/vegastrike.config
engine/src/vsfilesystem.cpp

These is a preliminary draft of the work I've promised to do in the previous PR.
I've intentionally separated the files to their own folder and library, as they are standalone and do not require any vegastrike headers.
The idea here is that GameConfig::LoadConfig is called very early in the game, and loads all settings to a private variable.
Then, when a struct is accessed for one of the fields in it, it is lazily populated by calling its constructor.
I may separate the structs to a different file (e.g. configuration.h) or several files (weapons_config.h), depending on its size.
I hope to add unit test to this and so have more robust tests. I am aware it currently has a bug that disabled movement.
**The ask here is for you to review this early in the process, to make sure you agree with …

Draft - Initial work on a configuration library

---

engine/src/cmd/movable.cpp

Code Changes:
Issues:
- #474 
Purpose:
- What is this pull request trying to do? Fix arithmetic exception that occurs while loading PWCU
PR Validation Tests have been run. This PR has been tested with both the PWCU and VS:UtCS datasets. Note, however, that Jenek's second mission caused an error in the Python assets:
```
TypeError: 'type' object is not subscriptable
```
apparently on [this line](https://github.com/vegastrike/Assets-Production/blob/e1242f004a84708548906c2c8c87cbaa180ffe4d/modules/campaign_lib.py#L361)

engine/src/cmd/movable.cpp: Apply ermo's suggested patch for arithmetic exception during PWCU game load

---

README.md
engine/FindGTK3.cmake

Code Changes:
Issues:
- #78
- #533 
Purpose:
Update `FindGTK3.cmake` so it can find GTK when installed with MacPorts.

Add macports include path to FindGTK3.cmake

---

.github/workflows/fortify-on-demand-scan.yml

Code Changes:
Issues:
- N/A
Purpose:
- What is this pull request trying to do? Change the `Fortify on Demand Scan` GitHub Action to run only when manually triggered
- What release is this for? Any
- Is there a project or milestone we should apply this to? Upcoming

Change the `Fortify on Demand Scan` to run only when manually triggered

---

.github/workflows/fortify-on-demand-scan.yml

Code Changes:
Issues:
Purpose:
- What is this pull request trying to do? Port #549 to 0.8.x

Change the `Fortify on Demand Scan` to run only when manually triggered - 0.8.x branch

---

engine/CMakeLists.txt
engine/FindLinuxDistro.cmake

- Enhancement: Move some of the packaging logic out of the primary CMakeLists.txt and into its own CMake module file.
- Bug Fix: Apparently `apt` is a program other than the Debian packager so use `dpkg-buildpackage` instead which is more accurate as well.
Code Changes:
Issues:
- #510 for master (0.9.x); will need to be ported to 0.8.x
Purpose:
- What is this pull request trying to do? Fix #510, improve the process across all distros

Bug Fix: properly detect DEB package tooling

---

.gitignore
engine/src/cmd/collision.cpp
engine/src/savegame.cpp
engine/src/savegame.h

Code Changes:
Issues:
- Fixes #516 for 0.8.x branch
Purpose:
- What is this pull request trying to do? Fix a bug where, with PWCU, Nav 8 is unexpectedly an object that you can crash into
- What release is this for? 0.8.x; 0.9.x pending

cmd/collision.cpp: Make it so that Nav 8 cannot be crashed into

---

engine/CMakeLists.txt
engine/src/cmd/armed.cpp
engine/src/cmd/armed.h
engine/src/cmd/damageable.cpp
engine/src/cmd/energetic.cpp
engine/src/cmd/energetic.h
engine/src/cmd/mount.cpp
engine/src/cmd/mount.h
engine/src/cmd/planet.h
engine/src/cmd/unit_csv.cpp
engine/src/cmd/unit_generic.cpp
engine/src/cmd/unit_generic.h
engine/src/damage/damageable_layer.h
engine/src/resource/resource.cpp
engine/src/resource/resource.h
engine/src/system_factory.h

This PR is part of a refactoring of the unit class. Specifically, it introduces the concept of resource.
A resource is any part of the game that can be used up and filled up.
The purpose of this class is to simplify code throughout the game by placing it here.
Instead of adding to health and then checking it isn't above max health, it's done automatically.
Money, energy, shield, armor are all examples of resource.
Note to reviewer:
This is a partial implementation of resource as a template. If I missed an overloaded operator or broke the rule of 0 or n, focus on that.
Code Changes:
Issues:
- Can't really die. Tried twice and ejected automatically. Couldn't respawn manually using the ; key.
- Milspec packages are broken. If you buy a ship with one, it will come with extra capabilities. You …

Task component

---

engine/CMakeLists.txt
engine/src/cmd/bolt.cpp
engine/src/cmd/bolt.h
engine/src/cmd/mount.cpp
engine/src/gfx/boltdrawmanager.cpp
engine/src/gfx/boltdrawmanager.h
engine/src/gfx/texture_manager.cpp
engine/src/gfx/texture_manager.h

Move away from the concept of decals to a simpler model where texture manager holds a master of every texture and copies it per shot.
Can't do the same for balls and animations because of weird life cycle issue of animations. They're destroyed before they should.
Code Changes:
- [Yes] Have the PR Validation Tests been run? See https://github.com/vegastrike/Vega-Strike-Engine-Source/wiki/Pull-Request-Validation
Issues:
- Shooting within the shield bubble of a base cause it to attack you. 
- Balls animation only use the first animation displayed. This is most likely a regression in the previous refactoring of bolt.cpp.
- Can't die in a collision. 
I'll open issues …

Further refactoring of bolt.cpp

---

.github/workflows/Windows-CI.yml
engine/vcpkg.json

Code Changes:
- [In Process] Have the PR Validation Tests been run? See https://github.com/vegastrike/Vega-Strike-Engine-Source/wiki/Pull-Request-Validation
Issues:
Purpose:
- What is this pull request trying to do? Fix the build on Windows by reverting Boost to version 1.77 instead of 1.78

Fix build issues with Boost 1.78 on windows by reverting to Boost 1.77 (alternate approach)

---

README.md

When running for the first time, Version.txt may not be present. Relative path may not work:
`Set data directory to ../Assets-Production
Error: Failed to find Version.txt anywhere.`
Instructions update per request at https://github.com/vegastrike/Vega-Strike-Engine-Source/issues/526#issuecomment-907832444

Clarify first run README instructions

---

engine/src/cmd/ai/aggressive.cpp
engine/src/cmd/csv.cpp
engine/src/cmd/drawable.cpp
engine/src/cmd/drawable.h
engine/src/cmd/tests/csv_tests.cpp
engine/src/cmd/tests/json_tests.cpp
engine/src/cmd/unit_csv.cpp
engine/src/cmd/unit_csv.h
engine/src/cmd/unit_csv_factory.cpp
engine/src/cmd/unit_csv_factory.h
engine/src/cmd/unit_generic.cpp
engine/src/cmd/unit_generic.h
engine/src/cmd/unit_json_factory.cpp
engine/src/cmd/unit_json_factory.h
engine/src/universe.cpp
engine/src/universe_util_generic.cpp

This PR introduces full support for both JSON and CSV unit files. 
At present, save games will use CSV.
Unless a release is planned soon, the coming one. 
Code Changes:
Issues:
- When died and respawned, ship was missing all modules and texture. Radar range was either random or max int. Non-reproducible.
- When landing on a planet, ship was incorrectly drawn. Non-reproducible.
- Multiple issues related to legacy code and correctness of assets (to be fixed there).

Remove old unit csv code and fully replace with modern json/csv support

---

engine/CMakeLists.txt

Code Changes:
- [Partly] Have the PR Validation Tests been run? See https://github.com/vegastrike/Vega-Strike-Engine-Source/wiki/Pull-Request-Validation
Issues:
- N/A
Purpose:
- What is this pull request trying to do? Simply increment the API version that the engine reports to the assets, for upcoming release series 0.9.x

CMakeLists.txt: Increment VEGASTRIKE_ASSETS_API_VERSION to 2

---

engine/CMakeLists.txt
engine/src/cmd/unit_csv.cpp
engine/src/cmd/unit_csv_factory.h
engine/src/cmd/unit_optimize_factory.cpp
engine/src/cmd/unit_optimize_factory.h
engine/src/universe.cpp

This is a first attempt to reduce units.json file size by moving ships to another file and making it hierarchical.
The aim is to write a identical value once. For example, all variants of the same ship (e.g. llama) share the folder, name, description, etc. If you write these in the parent llama, all variants will apply them. Have a different description for llama.begin, overwrite it for that variant specifically.
Currently, implemented only for Areus (and only for Areus variant) and Llama.begin.
See also related asset [98](https://github.com/vegastrike/Assets-Production/pull/98)
Code Changes:
- [not yet] Have the PR Validation Tests been run? See https://github.com/vegastrike/Vega-Strike-Engine-Source/wiki/Pull-Request-Validation
Issues:
- ~~In loaded game, shield reduce in power~~ …

Add ability to parse from ships.json, a hierarchical unit structure

---

engine/src/gnuhash.h

Code Changes:
- [Mostly] Have the PR Validation Tests been run? See https://github.com/vegastrike/Vega-Strike-Engine-Source/wiki/Pull-Request-Validation
Issues:
Purpose:
- What is this pull request trying to do? Move part of the contents of gnuhash.h out of the `std` namespace, in order to follow best practices, and possibly also in order to fix some compile errors that have cropped up recently.

Refactor gnuhash.h

---

.github/workflows/Windows-CI.yml
.github/workflows/codeql.yml
.github/workflows/fortify-on-demand-scan.yml
.github/workflows/gh-actions-pr.yml
.github/workflows/gh-actions-release.yml
.github/workflows/macos-ci.yml
.github/workflows/scorecards-analysis.yml
.gitignore
engine/src/gldrv/gl_init.cpp
engine/src/gldrv/gl_program.cpp

Code Changes:
Issues:
- Relates to #533 
Purpose:
- What is this pull request trying to do? Get the game working on macOS again, this time without all the changes from the PR 754 refactor. Also, update several of the GitHub Actions to the latest version available.
- What release is this for? 0.9.x, presumably
- Is there a project or milestone we should apply this to? 0.9.x, presumably
Additional Notes:
During play testing, I kept encountering crashes after loading certain savegames. (I think that at least some of these may be the same issue previously reported as #761 .) I also hit the crash in the `Mesh` destructor at least once. …

Get the game working on macOS again (without PR 754 changes)

---

.gitmodules

Code Changes:
Issues:
- n/a
Purpose:
- VS is no longer stronly linking the engine with the assets so the submodule linkage has not been maintained.

Bug Fix: Remove the gitsubmodule

---

engine/CMakeLists.txt

Code Changes:
Issues:
- #801 
Purpose:
Check that /etc/debian_version exists Before relying on it existing.
NOTE: The logic was originally setup for Debian distros; however, when run on a non-Debian distro with the Debian Packaging tools installed this file does not exist and in some cases it can cause a problem.

Bug Fix: Check for /etc/debian_version (0.8.x)

---

engine/CMakeLists.txt

Code Changes:
Issues:
- #801 
Purpose:
Check that /etc/debian_version exists Before relying on it existing.
NOTE: The logic was originally setup for Debian distros; however, when run on a non-Debian distro with the Debian Packaging tools installed this file does not exist and in some cases it can cause a problem.

Bug Fix: Check for /etc/debian_version

---

engine/src/cmd/script/script_statement.cpp
engine/src/gfx/aligned.h
engine/src/gfx/particle.cpp
engine/src/gfx/particle.h

Code Changes:
Issues:
-  CI build issue discovered in #805 
Purpose:
- What is this pull request trying to do? Compiler error on trying to concat a string and int.

Bug Fix: Manjaro Compilation on 0.8.x

---

engine/CMakeLists.txt
engine/src/cmd/basecomputer.h
engine/src/cmd/cargo_color.h
engine/src/cmd/carrier.cpp
engine/src/cmd/carrier.h
engine/src/cmd/script/script_call_unit_generic.cpp
engine/src/cmd/unit_csv.cpp
engine/src/cmd/unit_generic.cpp
engine/src/cmd/unit_generic.h
engine/src/cmd/weapon_factory.cpp
engine/src/main.cpp
engine/src/resource/cargo.cpp
engine/src/resource/cargo.h
engine/src/resource/manifest.cpp
engine/src/resource/manifest.h
engine/src/resource/tests/manifest_tests.cpp
engine/src/universe_util.h
engine/src/universe_util_generic.cpp

**This is a reopening of #816.**
This code decouple the MPL from rest of main body of code and make it and cargo part of resource lib. It makes it easier to test (some basic tests included) and also removes dependencies on the gfx folder among others.
This PR is part of a list of small PRs intended to come before https://github.com/vegastrike/Vega-Strike-Engine-Source/pull/810. They are intended to clear the way for it and reduce the actual code in it to a manageable level. Note that https://github.com/vegastrike/Vega-Strike-Engine-Source/pull/810 is a draft PR for review. Once these PR's are merged, I may break it up into smaller chunks for better processing.
Code Changes:
[x] Have the PR Validation Tests been run? See https://github.com/vegastrike/Vega-Strike-Engine-Source/wiki/Pull-Requ …

Task mpl 2

---

script/docker-entrypoint.sh

Code Changes:
Issues:
- none
Purpose:
- What is this pull request trying to do? Fix the release process
- Is there a project or milestone we should apply this to? 0.9.0-alpha3
The Build Process expects to find the output of the tests when doing a release. It is probably wise to run them all the time whether a PR or a release, so let's do so.

Bug Fix: Always run the unit tests

---

.github/workflows/Windows-Release.yml
.github/workflows/macos-release.yml

- Rename the workflows to match reality (Release not CI)
- Remove the final publisher as it does not support Mac/Win, only Linux. A new publisher will be needed to support those platforms

Bug Fix: Mac/Windows Release Builds

---

.github/workflows/Windows-Release.yml
.github/workflows/gh-actions-release.yml
.github/workflows/macos-release.yml

Code Changes:
Issues:
- #858
Purpose:
- unify to a single release artifact uploader for all platforms
- move to an official release artifact uploader instead of just an artifact uploader
- see https://github.com/softprops/action-gh-release for documentation on usage
- 0.9.0
- 0.9.x

Actions: migrate release artifact GH action

---

.github/workflows/Windows-Release.yml
.github/workflows/macos-release.yml
engine/CMakeLists.txt

Code Changes:
Issues:
- N/A?
Purpose:
- What is this pull request trying to do? Fix the filenames for the macOS DMG installer packages generated; get a single Windows installer format working, with the correct filename for that as well

Fix CPack package filenames; try to get one Windows installer working

---

engine/src/cmd/controls_factory.cpp
engine/src/configuration/configuration.cpp
engine/src/configuration/configuration.h
engine/src/configuration/graphics_config.cpp
engine/src/configuration/graphics_config.h
engine/src/resource/json_utils.cpp
engine/src/resource/json_utils.h

This fixes bug 937, which was somehow introduced to master.
Code Changes:
Issues:
- ship view produces an error in python because my assets are aligned to #936. Shouldn't be an issue otherwise.

Task fix 937 - missing json.h header

---

engine/src/cmd/unit_csv.cpp

Code Changes:
Issues:
Fixes #962 
Purpose:
- What is this pull request trying to do? Fix issue 962, complete loss of yaw controls due to zero values in savegame

unit_csv.cpp: Fix parsing of "Yaw_Governor_Right" and "Yaw_Governor_Left"

---

engine/src/main.cpp

This has been seen on void-linux x86_64, musl-libc
Code Changes:
Issues:
- May need to check if this is OK on macOS too (I think it should)
Purpose:
- What is this pull request trying to do? Fixing a POSIX non-compliance warning
- What release is this for? Next one
- Is there a project or milestone we should apply this to? Next one

Fix wrong <sys/signal.h> inclusion

---

engine/src/cmd/collide2/opcodetypes.h

Code Changes:
Issues:
- Please list any related issues : N/A
Purpose:
- What is this pull request trying to do? Fix compilation on void-linux x86_64 with musl libc
- What release is this for? current master HEAD
- Is there a project or milestone we should apply this to? Next one

Fix conflicting wchar_t definition error on musl libc

---

engine/src/universe_util.cpp
engine/src/universe_util.h
engine/src/universe_util_server.cpp

I could have named this PR "less to read"... ;-)
It is unused in those files.
The only use is in `engine/src/universe_util_generic.cpp` where I left it untouched. And where it is undefined at EOF.
Code Changes:
Issues:
- none ?
Purpose:
- What is this pull request trying to do? Remove dead code
- What release is this for? Next
- Is there a project or milestone we should apply this to? Next

Remove unused macro: activeSys

---

.github/workflows/Windows-CI.yml
.github/workflows/Windows-Release.yml
CMakeLists.txt
engine/src/gldrv/winsys.cpp
engine/src/main.cpp
script/bootstrap.ps1
script/build.ps1
script/package.ps1
vcpkg.json

Code Changes:
Issues Fixed:
- Fixes #1062 (joystick functionality)
- The game crashed a couple more times. Nothing necessarily new.
- Several more times, certain letters went missing from the HUD, like `n`, `p`, and `z`. This is not a new issue either. It is annoying to see it again though, especially several times in a row.
Purpose:
- What is this pull request trying to do? Sync the master branch with many of the latest packaging, scripting, CMake, and vcpkg changes on the 0.9.x branch. Also update the vcpkg `builtin-baseline` value, in order to pull the latest version of each of our dependencies available from vcpkg as of this date. And finally, fix the long-standing joystick issues.
- Is there a project or milestone we should …

vcpkg builtin-baseline, joystick, etc. 2025-03

---

engine/src/gldrv/gl_init.cpp
engine/src/gldrv/gl_init.h
engine/src/gldrv/gl_state.cpp
engine/src/in_joystick.h

Intentionally not touching the other ones:
- engine/src/endianness.h
- engine/src/lin_time.cpp
- engine/src/posh.h
As they are more involved, this is a first step in the right direction (hopefully)
Fixes: issue #995 (partly)
Code Changes:
Issues:
- Still some work to do after this first step
Purpose:
- What is this pull request trying to do? Remove dead code
- What release is this for? Next
- Is there a project or milestone we should apply this to? Next

Remove some IRIX ifdeffery

---

engine/src/cmd/movable.cpp
engine/src/configuration/configuration.h

Code Changes:
Issues:
- Fixes https://github.com/vegastrike/Assets-Masters/issues/63
Purpose:
- What is this pull request trying to do? Fix the non-combat speed multiplier, setting its value to 1000x, like it used to be

Correct non-combat speed multiplier to 1000x

---

engine/src/lin_time.cpp

This one should only keep the *really* uncontroversial part of:
https://github.com/vegastrike/Vega-Strike-Engine-Source/pull/1056
so that we can make some progress merging it piecemeal...

Assorted cleanups for lin_time.cpp - take 2

---

README.md

Code Changes:
Issues:
- Fixes #1094 
Purpose:
- What is this pull request trying to do? Document the fact that Python 3.11.8 must be installed alongside the game on Windows in order for the game to run.
- What release is this for? 0.9.1

README.md: Add a note about the separate Python installation requirement on Windows

---

CMakePresets.json

Code Changes:
Issues Fixed:
- N/A
- Same as before, I believe
Purpose:
- What is this pull request trying to do? Fix the MacPorts builds for compatibility with older versions of macOS, which have broken recently

April 2025 updates to MacPorts build infrastructure

---

engine/CMakeLists.txt

Code Changes:
- Fixes #1130 
- Nothing new that I'm aware of
Purpose:
- What is this pull request trying to do? Remove any Start Menu or desktop shortcuts created by this installer. Leave shortcut creation to the vsUTCS installer
- What release is this for? 0.9.1

0.9.x: Don't install any Start Menu shortcuts. Leave that to the Assets installer

---

engine/src/cmd/basecomputer.cpp
engine/src/resource/cargo.cpp
engine/src/resource/cargo.h
libraries/cmd/carrier.cpp
libraries/cmd/unit_csv.cpp
libraries/cmd/unit_generic.cpp

Fixes #1122
Fixes #1123 
- Prevent integral components from appearing on the upgrade buy side.
- When adding cargo, check if can add to existing entry
- Mark added integral components as integral in unit_csv
- Remove code from unit_generic. We deal with this in unit_csv when loading.
- Add integral attribute to cargo
Code Changes:
Tested changes in the following ways:
1. in Upgrade screen
2. In flight, checked components are listed properly.
3. Saved game and checked the json.
Issues:
- None related to my changes.

Fix #1122 and #1123

---

engine/src/cmd/beam.cpp

Fix: #1066
Culprit was a refactoring of heat_sink. This variable was 0 and did nothing in beam.cpp
```
void Beam::UpdatePhysics(const Transformation &trans,const Matrix &m,
Unit *targ,
float tracking_cone,
Unit *targetToCollideWith,
float HeatSink,
Unit *firer,
Unit *superunit) {
...
refiretime += simulation_atom_var * HeatSink;
return;
}
```
... except that in unit_generic.cpp, the calling function passed this as the heat_sink, turning 0 to 1:
`(HeatSink ? HeatSink : 1.0f) * mounts[i].functionality`
Code Changes:
No. It's a one liner fix and I understand the code now. 
Relying on the _pull request validation_ is how I got here. Llama.begin has no beam weapons.
Issues:
Purpose:
- Is …

Fix issue where beam weapons fire once

---

engine/src/components/drive.cpp

Fix: #1229 
The issue was that when reading a ship file we applied two settings, game_accel and game_speed to several drive attributes. When saving, we incorrectly divided the attributes by 1/game_speed and 1/game_accel.
The bug wasn't caught because both values were 1.
Code Changes:

Fix issue 1229

---

.github/workflows/Windows-CI.yml
.github/workflows/Windows-Release.yml
.github/workflows/macos-ci.yml
.github/workflows/macos-release.yml

Code Changes:
Issues:
- N/A
Purpose:
- What is this pull request trying to do? Remove the attempted Windows 2019 builds, so that our CI starts working again. Trimmed-down version of #1228 

Remove Windows 2019 builds (trimmed-down version)

---

script/bootstrap

Code Changes:
Issues:
- N/A
Purpose:
- What is this pull request trying to do? Drop SDL 1 and 1.2 from the bootstrap script at long last. All the versions of Vega Strike we currently support use SDL 2, so the time has come.
- What release is this for? 0.9.x and up, potentially
- Is there a project or milestone we should apply this to? In this PR, I'm making the change on the `master` branch. So it applies to 0.10.x.

script/bootstrap: Omit SDL 1 and 1.2; update copyleft header

---

engine/CMakeLists.txt
engine/src/cmd/basecomputer.cpp
engine/src/cmd/basecomputer.h
engine/src/cmd/reload_utils.cpp
engine/src/cmd/reload_utils.h
engine/src/components/cargo_hold.cpp
engine/src/components/components_manager.cpp
engine/src/components/components_manager.h
engine/src/resource/cargo.cpp
libraries/cmd/unit_csv.cpp
libraries/cmd/unit_generic.cpp
libraries/cmd/unit_generic.h
libraries/cmd/unit_util_generic.cpp

- Add description of ammo for guns with ammo
- Add reload button when supported and needed
- Display reload button only if gun isn't damaged. Otherwise display fix instead (not ideal)
- Code is by weapon type. So if one microdriver is damaged, you can't reload the other.
- Reload happens one gun at a time of same type. If you have 3 microdrivers with 88%/33%/2%, you'd have to reload the first two first.
Code Changes:
Issues:
- See above
- Did not delete units such as Hephaestus_Mini_ammo__upgrades yet. Once approved, we could delete real ammo but I'm not sure about missiles.

Add ability to reload guns 
