vegastrike/Vega-Strike-Engine-Source

- .travis.yml
- README.md
Created initial .travis.yml based on https://github.com/BenjamenMeyer/samplingEngine/blob/master/.travis.yml, offered by @BenjamenMeyer.
Resolves #31
> Integrate Travis-CI

- .travis.yml
- engine/setup/src/include/central.cpp
- engine/setup/src/include/display_gtk.cpp
- engine/setup/src/include/file.cpp
- engine/setup/src/include/general.cpp
- engine/src/aldrv/al_sound.cpp
- engine/src/audio/renderers/OpenAL/OpenALRenderer.cpp
- engine/src/gfx/cockpit.cpp
- engine/src/gfx/nav/navitemstodraw.h
- engine/src/gldrv/gl_light_state.cpp
- engine/src/gldrv/hashtable_3d.h
Did some minor refactoring to let compilation pass with the Clang compiler.
Removed Clang from allowed failures in Travis-CI.
Tested on Archlinux with Clang-9.0.1.
From a minor test, game-play seems unaffected.
> (refactor) Fix clang compilation

- doc/man/vegastrike.1
- engine/setup/src/include/display.h
- engine/vegastrike.spec
- sh/vsinstall.sh
Updating version in master to 0.6.0
NOTE: This does not necessarily mean the next release will be 0.6.0... it could be 1.0; just breaking the version chain from the 0.5.x series in master, and provide us with a bit more freedom to change things up. This is more to say, we're not going to have another `0.5.x` release from `master` than anything else.
> Update: Version to 0.6.0

- engine/src/audio/RenderableListener.cpp
- engine/src/audio/RenderableSource.cpp
- engine/src/audio/Source.cpp
- engine/src/audio/Stream.cpp
- engine/src/audio/TemplateManager.cpp
- engine/src/audio/codecs/OggCodec.cpp
- engine/src/audio/renderers/OpenAL/OpenALRenderableStreamingSource.cpp
- engine/src/audio/renderers/OpenAL/OpenALSimpleSound.cpp
- engine/src/audio/renderers/OpenAL/OpenALStreamingSound.cpp
- engine/src/audio/test.cpp
- engine/src/cmd/base_util.cpp
- engine/src/command.cpp
- engine/src/gfx/ani_texture.cpp
- engine/src/gfx/mesh_gfx.cpp
- engine/src/gfx/technique.cpp
- engine/src/gfx/vid_file.cpp
- engine/src/gfx/vsimage.cpp
- engine/src/star_system_generic.cpp
The fix is based on [this](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#e15-catch-exceptions-from-a-hierarchy-by-reference) and [this](https://github.com/leela-zero/leela-zero/pull/2134/files)
Didn't test gameplay yet.
> Fixed -Wcatch-value warnings

- CONTRIBUTING.rst
> Contributing guidelines for the 0.6.x branch

- engine/CMakeLists.txt
- engine/objconv/CMakeLists.txt
- engine/objconv/mesher/CMakeLists.txt
- engine/setup/CMakeLists.txt
- All CMake Directives are upper-case
- All If-Block Statements have a space between the directive and the opening brace
- Consistency with braces on various lines
- Consistency in formatting (all tabs expanded, 4 space indents, all block levels indented, etc)
Code Changes:
> Enhancement: Standardize CMakeLists.txt

- README.md
Code Changes:
- Restructured the file 
- Removed redundant formatting
- Added contributors and backers info
- Updated some URLs
Issues:
- None
Purpose:
- Make the README's structure more logical
- Add more relevant info about the game and the project
> [skip ci] Refactor README.md

- doc/man/vegastrike.1
- engine/setup/src/include/display.h
- engine/vegastrike.spec
- sh/vsinstall.sh
Code Changes:
Issues:
- None
Purpose:
- Bump master's version to 0.7.0 since 0.6.x branch was created.
> Bumped version to 0.7.0

- .gitignore
- .travis.yml
- README.md
- engine/CMakeLists.txt
- sh/vspackage.sh
Adds support for CMake's CPack module for generating packages.
Built the Linux packages and Debian package; but have not tried to use it.
We still need to figure out the proper dependencies, but this at
least shows how it would work.
Contributes To: #131
Code Changes:
NOTE: This would need to be backported to the 0.6.x branch.
> Enhancement: CPack Support

- .gitignore
- .travis.yml
- README.md
- engine/CMakeLists.txt
- sh/vspackage.sh
This is a cherry-picked version of #135 for the 0.6.x branch.
> Enhancement packaging 0.6.x

- .gitignore
- engine/src/cmd/ai/firekeyboard.cpp
- engine/src/lin_time.cpp
Code Changes:
Issues:
**Fix the equivalent issue to #157 , only on the `master` branch.**
Purpose:
- What is this pull request trying to do? **Make Pause and Resume work properly on the `master` branch**
- What release is this for? **0.7.x and following**
- Is there a project or milestone we should apply this to? **0.7.x?**
> Fix resume crash on master

- engine/CMakeLists.txt
Code Changes:
Issues:
**Closes #173** 
Purpose:
- What is this pull request trying to do? **Make debugging Vega Strike easier by improving the debug configuration options**
> CMake: Improve debug optimization in C/C++ debug config

- engine/src/vsfilesystem.cpp
Code Changes:
Issues:
**Fixes #180** 
Purpose:
- What is this pull request trying to do? **Fix the potential buffer overflows in vsfilesystem.cpp**
**0.7.0, and possibly 0.6.0 as well.**
> vsfilesystem.cpp: Fixes potential path buffer overflows

- engine/CMakeLists.txt
Code Changes:
Issues:
Purpose:
- What is this pull request trying to do? Name the .deb packages appropriately
- What release is this for? 0.6.0
- Is there a project or milestone we should apply this to? 0.6.0 Release
> CPack: Rename vsUTCS => Vega-Strike

- engine/src/cmd/ai/hard_coded_scripts.cpp
- engine/src/cmd/unit_generic.cpp
Code Changes:
Issues:
#226  - enum constant in boolean context
#233 - enum constant in boolean context
Purpose:
Clear two compiler errors
Any
Nope
> Fixes the two enums being compared to booleans

- engine/src/cmd/damageable.cpp
- engine/src/cmd/drawable.cpp
- engine/src/cmd/planetary_orbit.cpp
- engine/src/cmd/unit_generic.cpp
- engine/src/galaxy_gen.cpp
- engine/src/gfx/mesh_fx.cpp
- engine/src/gfx/nav/navscreen.cpp
- engine/src/gfx/vdu.cpp
- engine/src/load_mission.cpp
- engine/src/rendertext.cpp
- engine/src/system_factory.cpp
Code Changes:
Issues:
#230 - Unused variable 'mis2' - Partial fix, there are more problems there
#232 `*` in boolean context
#233 - if clause does not protect - Partial fix, there are more problems there
#234 - unused variable 'div2pi'
#236 - unnecessary parenthesis in declaration 'g' 
#237 - unused variable 'fightername'
#238 - variable 'color' set and not used
#242 - variable 'iter' set and not used
#243 - `*` in boolean context
#244 - unused variable 'itemscale'
#247 - unused variable 'network_draw_messages'
Purpose:
Clean up the compile logs. There are several warnings there.
- What …
> A few easy fixes sprinkled all around

- README.md
Code Changes:
Issues:
- Typoes & glitches in the README file
Purpose:
fix the above
next one
next one
> Fix some glitches & typos in README.md

- engine/src/main.cpp
Code Changes:
Issues:
#318 
Purpose:
This fixes a core dump on startup on my system
Any
Not really
> Fixes a crash on my system

- engine/setup/src/include/general.cpp
Code Changes:
Issues:
#258 
Purpose:
Fixes a compiler warning for vegasettings. 
The compiler was complaining that strncpy plus the full length of the source is the same as strcpy without the length check. 
any
nope
> Fixes a compiler warning in vegasettings/src/include/general.cpp

- engine/setup/src/include/file.cpp
- engine/src/audio/Listener.h
- engine/src/gfx/jpeg_memory.cpp
- engine/src/gfx/jpeg_memory.h
- engine/src/gldrv/gl_light_pick.cpp
Code Changes:
Issues:
#257 
#253 
#249 
#248 
Purpose:
Clear some compiler warnings without changing the game in any way
Any
Nope.
> Compiler fixes 4

- engine/objconv/mesher/to_BFXM.cpp
- engine/objconv/mesher/to_BFXM.h
- engine/src/cmd/weapon_xml.cpp
- engine/src/cmd/weapon_xml.h
- engine/src/gfx/mesh_xml.cpp
- engine/src/gfxlib_struct.h
- engine/src/gldrv/gl_light_state.cpp
General fixes to clean up compiler warnings, round 5
Code Changes:
Issues:
#231 
#240 
#254 
#259 
Purpose:
Clean up compiler warnings.
Any
Nope
> Compiler fixes round 5

- .github/workflows/ci.yml
Code Changes:
Issues:
Purpose:
- What is this pull request trying to do? Get releases to actually build something!
> Let's try this again (GH Actions CD)

- .github/workflows/ci.yml
- script/cibuild
- script/docker-entrypoint.sh
Code Changes:
Issues:
#382 
Purpose:
- What is this pull request trying to do? Try yet again to get build artifacts to upload automatically when a release is created
> Chore/GH Actions CD Try Again

- engine/CMakeLists.txt
Code Changes:
Issues:
Closes #391 
Purpose:
- What is this pull request trying to do? Fix #391 on master
- What release is this for? 0.8.0
> CPack: Add libboost-date-time1.58.0 as dependency for bionic .deb's

- .github/workflows/codeql.yml
Code Changes:
Issues:
#382 
Purpose:
- What is this pull request trying to do? Add CodeQL scanning back to our repository
- What release is this for? Any
- Is there a project or milestone we should apply this to? 0.7.x and 0.8.x, both, I imagine
> Add codeql.yml back in

- .github/workflows/gh-actions-release.yml
Code Changes:
Issues:
N/A
Purpose:
- What is this pull request trying to do? Fix the CD for releases, which is still failing
> GH Actions - Release: Troubleshoot CD further

- .github/workflows/gh-actions-release.yml
Code Changes:
Issues:
#401 
Purpose:
- What is this pull request trying to do? Fix file conflicts when releasing 0.7.0 betas
> CD: GH Actions - Release: Omit source from deployed artifacts (0.7.x series)

- README.md
Code Changes:
Issues:
#354 
Purpose:
- What is this pull request trying to do? Document simpler option for installing dev dependencies. Also, fix broken CI icon on repository home page.
- What release is this for? 0.8.x, presumably
> README.md: Comment out CI icon again; add script/bootstrap instructions

- README.md
Code Changes:
Issues:
Closes #354 
Purpose:
- What is this pull request trying to do? Simplify the bootstrapping instructions for building on Linux; also, fix/update the CI icon
- What release is this for? 0.7.x
> Docs/Update Readme Jan 2021 on 0.7.x

- .github/workflows/gh-actions-release.yml
Code Changes:
Issues:
Purpose:
- What is this pull request trying to do? Fix the filters that control which artifacts are uploaded on releases
- What release is this for? 0.7.x
> Fix/ARTIFACT_EXT Syntax

- .github/workflows/gh-actions-release.yml
Code Changes:
Issues:
N/A
Purpose:
- What is this pull request trying to do? Fix one remaining artifact file pattern in error: the one for the source build
- What release is this for? 0.7.x
> GH Actions - Release: Fix ARTIFACT_EXT for source build

- doc/man/vegastrike.1
Code Changes:
Issues:
- Porting #412 from 0.7.x to master (0.8.x)
Purpose:
Port the man page changes from #412 to master.
> Enhancement updating the manpage 0 8 x

- script/package
Code Changes:
Issues:
- #391 
Purpose:
Version of #423 for master.
> Bug Fix: script/package - path to binaries (master)

- engine/CMakeLists.txt
Code Changes:
Issues:
- n/a
Purpose:
- clean up from #427 to fix the cmake directive capitalization
> Bug Fix: CMake directives to be upper-case

- README.md
Add some documentation about the helper scripts
Code Changes:
Issues:
- https://github.com/vegastrike/Assets-Masters/issues/23
Purpose:
Document the helper scripts that @evertvorster created.
> Bug Fix: Document the helper scripts

- doc/man/vegastrike-engine.1
- engine/CMakeLists.txt
- engine/setup/src/include/display.h
- engine/src/main.cpp
- engine/vegastrike.spec
- script/install
Skipping Windows Release related files
Code Changes:
Issues:
- n/a
Purpose:
- update version in master
> Update version to 0.9.x

- script/build.ps1
Code Changes:
Issues:
Purpose:
- What is this pull request trying to do? Remove some unnecessary prompts to overwrite files during the build process
- What release is this for? 0.9.x. Going to make the same changes for 0.8.x separately.
> script/build.ps1: Add /y argument to xcopy commands

- engine/setup/src/include/general.cpp
Code Changes:
Issues:
- Closes #430 
Purpose:
- What is this pull request trying to do? Refactor the `ptr_copy()` function the way we agreed to, as spelled out in #430 
> general.cpp: Implement ptr_copy as specified in issue 430

- engine/src/cmd/basecomputer.cpp
- engine/src/cmd/script/director_generic.cpp
- engine/src/savegame.cpp
- engine/src/savegame.h
Code Changes:
Issues:
- https://github.com/vegastrike/Vega-Strike-Engine-Source/pull/463
- #149 
Purpose:
Backports #463 from master to 0.8.x
> Backport 463 0.8.x

- README.md
Code Changes:
Issues:
- Closes #354 
- Partially addresses #123 
- Closes https://github.com/vegastrike/Assets-Masters/issues/23
Purpose:
- What is this pull request trying to do? Port #503 to master
- What release is this for? 0.9.x/1.0.x
- Is there a project or milestone we should apply this to? 0.9.x/1.0.x
> README.md: Windows support; binary name changes; vsettings script; etc.

- README.md
Code Changes:
Issues:
- N/A
Purpose:
- What is this pull request trying to do? Fix some minor issues that VSCode's markdown linter caught
> README.md: Fix (mostly minor) markdown linting issues, etc.

- engine/src/cmd/jump_capable.cpp
- engine/src/main.cpp
- engine/src/savegame.cpp
- engine/src/universe_util_generic.cpp
- engine/src/vs_globals.h
- engine/src/vsfilesystem.cpp
- engine/src/vsfilesystem.h
Code Changes:
- [In Progress] Have the PR Validation Tests been run? See https://github.com/vegastrike/Vega-Strike-Engine-Source/wiki/Pull-Request-Validation
Issues:
Purpose:
- What is this pull request trying to do? Fix some CodeQL warnings. And in the process, refactor some code so that, for example, the startup sequence on Win32 matches that on other platforms more closely.
> Fix/CodeQL Warnings 2021-09 (Part 1)

- engine/src/cmd/drawable.cpp
- engine/src/cmd/drawable.h
- engine/src/cmd/unit.cpp
- engine/src/cmd/unit.h
- engine/src/cmd/unit_generic.cpp
- engine/src/cmd/unit_generic.h
- engine/src/gfx/technique.cpp
This PR moves and refactors some unit.cpp code to Drawable class and some other places. It is for any coming release and no specific milestone.
Code Changes:
- [Yes] Have the PR Validation Tests been run? See https://github.com/vegastrike/Vega-Strike-Engine-Source/wiki/Pull-Request-Validation
Issues:
- None identified
> Minor refactoring of GameUnit

- .github/workflows/Windows-CI.yml
Code Changes:
Issues:
- N/A
Purpose:
- What is this pull request trying to do? Fix the Windows Continuous Integration!
- What release is this for? 0.9.x; 0.8.x pending
- Is there a project or milestone we should apply this to? 0.9.x; 0.8.x pending
> Fix Windows CI (python3 build)

- .github/workflows/Windows-CI.yml
Code Changes:
Issues:
- N/A
Purpose:
- What is this pull request trying to do? Fix the Windows CI (Continuous Integration) for the 0.8.x release / branch
> Windows-CI: Sync up with master branch, fixing py3 build

- Dockerfile
- script/cibuild
- script/docker-entrypoint.sh
Code Changes:
Issues:
- N/A
Purpose:
- What is this pull request trying to do? Port a minor set of changes from 0.8.x forward to master / 0.9.x
> Dockerfile, scripts: Correct issue with passing multiple FLAGS to Docker

- script/build.sh
Code Changes:
- [Minimally, yes] Have the PR Validation Tests been run? See https://github.com/vegastrike/Vega-Strike-Engine-Source/wiki/Pull-Request-Validation
Issues:
- Addresses #606 
Purpose:
- What is this pull request trying to do? Improve the build script's handling of paths and parameters that contain spaces
- What release is this for? 0.9.x; should perhaps address this in 0.8.x as well
- Is there a project or milestone we should apply this to? 0.9.x; maybe 0.8.x in a later PR
> script/build.sh: Improve handling of paths and parameters with spaces

- engine/CMakeLists.txt
Peer review on PR #614 found a duplication after the PR was merged.
This is to clean that up.
Code Changes:
Issues:
- #614 - https://github.com/vegastrike/Vega-Strike-Engine-Source/pull/614#discussion_r762648964
Purpose:
- Peer Review fix for issue found post merge
> Peer Review: Remove duplication

- engine/src/cmd/damageable.cpp
Code Changes:
- [In Progress] Have the PR Validation Tests been run? See https://github.com/vegastrike/Vega-Strike-Engine-Source/wiki/Pull-Request-Validation
Issues:
- Closes #600 
Purpose:
- What is this pull request trying to do? Fix #600 , the issue where the player simply can't die
> Fix issue preventing player from dying

- doc/ASSET_API.rst
Introduction of the Asset API change log documentation.
Code Changes:
Issues:
- #349
Purpose:
Add a change log for the Asset API so game asset devs can easily determine which version they need to check for.
> Enhancement: Asset API change log documentation

- engine/src/cmd/unit_csv.cpp
- engine/src/cmd/unit_csv_factory.h
Code Changes:
Issues:
- Closes #636 
Purpose:
- What is this pull request trying to do? Fix the issue where the game does not recognize when you have a jump drive after purchasing a new ship
> Fix "no jump drive present" issue

- engine/CMakeLists.txt
- engine/src/gfx/cockpit.cpp
- engine/src/gfx/cockpit.h
- engine/src/gfx/cockpit_generic.h
- engine/src/gfx/cockpit_gfx.cpp
- engine/src/gfx/cockpit_gfx.h
- engine/src/gfx/cockpit_gfx_utils.cpp
- engine/src/gfx/cockpit_gfx_utils.h
Also try to fix IDE complaints about unknown size_t and FLT_MAX by adding relevant headers. Doesn't seem to solve it at my end but leaving anyway, as it's good practice.
This replaces the much more ambitious but ultimately unsuccessful #655. I've copied some of the code from it and packaged it in this PR.
Code Changes:
- [Yes] Have the PR Validation Tests been run? See https://github.com/vegastrike/Vega-Strike-Engine-Source/wiki/Pull-Request-Validation
Issues:
- None
Purpose:
- What is this pull request trying to do? Just general code refactoring
- What release is this for? Any
- Is there a project or milestone we should apply this to? No
> Move cockpit draw code to cockpit_gfx

- engine/src/system_factory.cpp
Code Changes:
- [In Progress] Have the PR Validation Tests been run? See https://github.com/vegastrike/Vega-Strike-Engine-Source/wiki/Pull-Request-Validation
Issues:
- Fixes #663 
Purpose:
- What is this pull request trying to do? Fix the crash when loading Sol:Sol
- What release is this for? 0.9.x, probably
- Is there a project or milestone we should apply this to? 0.9.x, probably
> Fix crash loading Sol:Sol

- script/bootstrap
Code Changes:
Issues:
Purpose:
- What is this pull request trying to do? Add Manjaro support to the bootstrap script
- What release is this for? 0.9.x?
- Is there a project or milestone we should apply this to? 0.9.x?
> script/bootstrap: Add Manjaro; minor cleanup

- engine/src/cmd/weapon_factory.cpp
- engine/src/cmd/weapon_factory.h
Engine code to support the switch.
Note that this change and the previous one to units will break Wing Commander.
Code Changes:
Issues:
- There are previous issues in the weapon_list that should be addressed at some point.
- The JSON library does not conform to the standard, making the code sloppier than I would have liked.
- Old files (units.csv and weapon_list.xml) have not been deleted yet.
> Convert weapon_list.xml to weapons.json

- engine/src/cmd/carrier.cpp
This makes carrier read the master parts list from json and not csv.
See also https://github.com/vegastrike/Assets-Production/pull/95
Code Changes:
Issues:
- None identified
> Convert master_part_list read code from csv to json

- engine/src/gfx/particle.cpp
- engine/src/gfx/particle.h
Code Changes:
- [In Progress] Have the PR Validation Tests been run? See https://github.com/vegastrike/Vega-Strike-Engine-Source/wiki/Pull-Request-Validation
Issues:
- #718 
Purpose:
- What is this pull request trying to do? Refactor how the game engine handles particles (i.e. those trailing from behind damaged ships). Also fix how it removes obsolete particles from the particle collection(s).
Notes:
I have play-tested this set of changes some. It does not seem to introduce any new problems, but neither have I been able to confirm …
> Particle Refactor

- engine/CMakeLists.txt
- engine/src/resource/product.cpp
- engine/src/resource/product.h
- engine/src/resource/resource.cpp
- engine/src/resource/resource.h
- engine/src/resource/store.cpp
- engine/src/resource/store.h
- engine/src/resource/tests/buy_sell.cpp
- engine/src/resource/tests/resource_test.cpp
- Fix bug in resource
- Add tests for resource and store
I have added unit tests instead of the standard tests as the code has not yet been integrated with engine.
I am waiting for @stephengtuggy 's changes, as he's touching the same areas of the code.
Code Changes:
Issues:
- None
Purpose:
- What is this pull request trying to do? Make the code cleaner.
> Add code for store and customer

- engine/src/cmd/csv.cpp
- engine/src/cmd/csv.h
- engine/src/cmd/unit_csv.cpp
- engine/src/cmd/unit_csv_factory.h
closes #747 
Code Changes:
_I've also ran some basic tests and ran extensive tests on the specific problem in question._
Issues:
- Overwriting save game, leaves the old ship file in the ship folder if it is not the same. #755
> Fix save game bug

- engine/src/resource/store.cpp
- engine/src/resource/store.h
- engine/src/resource/tests/buy_sell.cpp
closes #751
Also add tests and a few additional methods to store.
Code Changes:
> Fix bug - Store::Subtract adds quantity instead of subtracting it

- engine/CMakeLists.txt
- engine/src/cmd/audible.h
- engine/src/cmd/carrier.cpp
- engine/src/cmd/energetic.h
- engine/src/cmd/movable.cpp
- engine/src/cmd/movable.h
- engine/src/cmd/ship.cpp
- engine/src/cmd/ship.h
- engine/src/cmd/unit_generic.cpp
- engine/src/cmd/unit_generic.h
- Split master_part_list to multiple files
- Make ship into a separate super class of unit
- Move additional methods to movable
Code Changes:
Issues:
- Ship was damaged after respawning
**Note: this required the complementing changes to data files.**
> Further refactoring of unit code

- .github/workflows/Windows-CI.yml
- .github/workflows/codeql.yml
- .github/workflows/fortify-on-demand-scan.yml
- .github/workflows/gh-actions-pr.yml
- .github/workflows/gh-actions-release.yml
- .github/workflows/macos-ci.yml
- .gitignore
- engine/src/cmd/basecomputer.cpp
- engine/src/cmd/collide2/opcodetypes.h
- engine/src/endianness.h
- engine/src/gfx/aligned.h
- engine/src/gfx/jpeg_memory.h
- engine/src/gfx/particle.h
- engine/src/gldrv/gl_globals.h
- engine/src/gldrv/gl_init.cpp
- engine/src/gldrv/gl_program.cpp
- engine/src/vsfilesystem.cpp
Code Changes:
Issues:
- Fixes #78 for 0.8.x
- Fixes #533 for 0.8.x (I think)
Purpose:
- What is this pull request trying to do? Introduce macOS support to the 0.8.x series of releases (making the game compilable, as well as playable)
- Is there a project or milestone we should apply this to? Not sure
> macOS support for 0.8.x release series

- engine/CMakeLists.txt
Code Changes:
Issues:
- CI build issue discovered in #805 
Purpose:
- What is this pull request trying to do? Fix the Windows CI builds for 0.8.x
> Bug Fix: Windows Build on 0.8.x

- .github/workflows/Windows-Release.yml
- .github/workflows/macos-release.yml
- script/build.ps1
Code Changes:
Issues:
- not yet
Purpose:
- What is this pull request trying to do? Capture artifacts for Windows and Mac on release builds
> Enhancement: Mac/Win Release processes

- .github/workflows/macos-release.yml
Issues:
Purpose:
- What is this pull request trying to do? Fix the packaging step for macOS releases
> macOS Releases: Fix Packaging Step (0.9.x)

- .github/workflows/macos-ci.yml
- .github/workflows/macos-release.yml
- engine/CMakeLists.txt
Code Changes:
Issues:
Addresses #929 
Purpose:
- What is this pull request trying to do? Get the installer packaging to work for Mac
> More On Packaging - 0.9.x

- .github/workflows/Windows-Release.yml
- .github/workflows/macos-release.yml
- engine/CMakeLists.txt
- engine/CMakePresets.json
- script/build.ps1
- script/package.ps1
- script/test.ps1
Code Changes:
Issues:
- N/A?
Purpose:
- What is this pull request trying to do? Finish fixing the macOS and Windows release packaging process
> Yet More On Packaging - 0.9.x

- engine/CMakeLists.txt
- engine/setup/CMakeLists.txt
Code Changes:
Issues:
- N/A
Purpose:
- What is this pull request trying to do? Get the macOS 13 installer working for the 0.9.x series
> Fix macOS installer - 0.9.x

- engine/src/gldrv/winsys.cpp
Code Changes:
Issues:
Closes #961 
Uncovers #966 
Purpose:
- What is this pull request trying to do? Fix issue 961, VSExit() not exiting the game properly
> winsys.cpp: Actually exit the game in winsys_exit() (Fix Issue 961, with minimal code changes)

- .github/workflows/Windows-CI.yml
- .github/workflows/Windows-Release.yml
- .github/workflows/codeql.yml
- .github/workflows/fortify-on-demand-scan.yml
- .github/workflows/gh-actions-pr.yml
- .github/workflows/gh-actions-release.yml
- .github/workflows/macos-ci.yml
- .github/workflows/macos-release.yml
- .github/workflows/scorecards-analysis.yml
- engine/CMakeLists.txt
- engine/CMakePresets.json
Code Changes:
- 0.9.x macOS CI not working reliably
Issues Observed (Outstanding Issues):
- No new issues particularly
Purpose:
- What is this pull request trying to do? Fix the 0.9.x macOS CI
> Python version wrangling 0.9.x

- script/bootstrap.ps1
Code Changes:
Issues:
Purpose:
> Remove setting PYTHONHOME for Windows builds

- README.md
Document how others can minimize downloads, specifically for maintainers of systems like Gentoo, Arch, etc.
Closes #83
Code Changes:
Issues:
- #83 
Purpose:
- What is this pull request trying to do? Provide a way to reduce download bloat
- What release is this for? N/A
- Is there a project or milestone we should apply this to? N/A
> Enhancement: Minimize Download Size

- README.md
This is just fixing the README build instructions
> Fix README build instructions

- engine/src/cmd/csv.cpp
- engine/src/cmd/drawable.cpp
- engine/src/cmd/energetic.cpp
- engine/src/cmd/role_bitmask.cpp
- engine/src/cmd/unit_csv.cpp
- engine/src/gfx/mesh.cpp
- engine/src/gfx/mesh.h
- engine/src/gfx/mesh_gfx.cpp
- engine/src/gfx/mesh_xml.cpp
- engine/src/hashtable.h
Code Changes:
Issues:
- Fixes #1032 
Purpose:
- What is this pull request trying to do? Fix jumping, and possibly SPEC mode as well, for 0.9.x
> Fix Jumping - 0.9.x

- engine/src/python/python_class.h
Code Changes:
Issues:
- only tested on linux
Purpose:
- What is this pull request trying to do? remove useless code
- What release is this for? next
- Is there a project or milestone we should apply this to? next
> Remove doubly-included "init.h"

- engine/src/python/init.h
Code Changes:
Issues:
- Only tested on linux
Purpose:
- What is this pull request trying to do? cleanup unused code
- What release is this for? next
- Is there a project or milestone we should apply this to? next
> Remove useless `Vector/Vactor` macro definition hack for old VC compiler

- .github/workflows/macos-ci.yml
- .github/workflows/macos-release.yml
- CMakeLists.txt
Code Changes:
Issues Fixed:
- N/A
- Probably the same as before
Purpose:
- What is this pull request trying to do? Update the version of Python we request and use in the macOS GitHub Actions workflows, both so that we gain the advantages of the newer Python patch version, and to speed up the CI builds since we will again be using a Python version that comes preinstalled on the GitHub Actions runners.
> Update macOS CI Python version

- LICENSE
- libraries/gfx_generic/CMakeLists.txt
- libraries/gfx_generic/boltdrawmanager.cpp
- libraries/gfx_generic/boltdrawmanager.h
- libraries/gfx_generic/cockpit_generic.cpp
- libraries/gfx_generic/cockpit_generic.h
- libraries/gfx_generic/lerp.cpp
- libraries/gfx_generic/lerp.h
- libraries/gfx_generic/matrix.cpp
- libraries/gfx_generic/matrix.h
- libraries/gfx_generic/mesh.cpp
- libraries/gfx_generic/mesh.h
- libraries/gfx_generic/mesh_bxm.cpp
- libraries/gfx_generic/mesh_bxm.h
- libraries/gfx_generic/mesh_io.h
- libraries/gfx_generic/mesh_poly.cpp
- libraries/gfx_generic/mesh_xml.cpp
- libraries/gfx_generic/mesh_xml.h
- libraries/gfx_generic/quaternion.cpp
- libraries/gfx_generic/quaternion.h
- libraries/gfx_generic/soundcontainer_generic.cpp
- libraries/gfx_generic/soundcontainer_generic.h
- libraries/gfx_generic/sphere.h
- libraries/gfx_generic/sphere_generic.cpp
- libraries/gfx_generic/texture_manager.cpp
- libraries/gfx_generic/texture_manager.h
- libraries/gfx_generic/tvector.cpp
- libraries/gfx_generic/tvector.h
- libraries/gfx_generic/vec.h
- script/add_gpl_license.py
Code Changes:
Issues Fixed:
- Contributes to #547 
- Should be the same as before. No functional changes, except to the add_gpl_license.py script.
Purpose:
- What is this pull request trying to do? Update the copyleft headers at the top of a manageable subset of the game engine's files
> Update copyleft headers in the files under libraries/gfx_generic

- engine/src/cmd/beam.cpp
- engine/src/cmd/bolt.cpp
- libraries/gfx_generic/boltdrawmanager.cpp
- libraries/root_generic/options.cpp
- libraries/root_generic/options.h
Code Changes:
Issues Fixed:
- Guns only able to fire once. (At least, it's possible that this fixes that. Certainly I can now keep firing "Lasers" on an ongoing basis, whenever I have enough weapon capacitor charge.)
- Can still dock to any station from anywhere in the system
- Oswald and other NPCs become hostile for no good reason still
Purpose:
- What is this pull request trying to do? Migrate another setting to configuration(), possibly fixing the guns-not-working problem in the process
> Migrate the BlendGuns setting to configuration()->graphics.blend_guns

- engine/src/cmd/missile.cpp
- engine/src/gfx/cockpit.cpp
- libraries/cmd/dock_utils.cpp
- libraries/cmd/jump_capable.cpp
- libraries/cmd/unit_generic.cpp
- libraries/root_generic/options.cpp
- libraries/root_generic/options.h
- libraries/root_generic/universe_util_generic.cpp
- libraries/root_generic/vsfilesystem.cpp
Code Changes:
Issues Fixed:
- Fixes #1092 
- Fixes #1107 
- Fixes #1070 
Purpose:
- What is this pull request trying to do? Fix docking with stations, etc.!
> Fix Docking

- README.md
- engine/CMakeLists.txt
Code Changes:
Issues:
- Fixes #1129 
Purpose:
- What is this pull request trying to do? Update the 0.9.1 documentation regarding the Python installation requirement
- What release is this for? 0.9.1
> README.md: Update Python requirement listed to Python 3.12

- engine/src/components/shield.cpp
It was too slow before.
Fix: #1158 
Code Changes:
> Fix shield dissipation

- engine/src/cmd/ai/firekeyboard.cpp
- engine/src/cmd/ai/flykeyboard.cpp
- engine/src/cmd/basecomputer.cpp
- engine/src/cmd/beam.cpp
- engine/src/cmd/cargo_color.h
- engine/src/cmd/script/director_generic.cpp
- engine/src/components/shield.cpp
- engine/src/gfx/nav/navscreen.cpp
- engine/src/gui/picker.cpp
- engine/src/gui/slider.cpp
- engine/src/gui/staticdisplay.cpp
- engine/src/main.cpp
- libraries/cmd/carrier.cpp
- libraries/cmd/unit_generic.cpp
- libraries/cmd/upgradeable_unit.cpp
- libraries/root_generic/configxml.cpp
- libraries/root_generic/options.cpp
- libraries/root_generic/vsfilesystem.cpp
- script/convert_config_section.py
Code Changes:
- Closes #1194 
- Closes #1195 
- Closes #1197 
- Closes #1198 
- Closes #1199 
- Closes #1201 
- Closes #1202 
- Closes #1203 
- Closes #1204 
- Closes #1205 
- Closes #1190 
- Closes #1182 
- Fixes #1223 
- Selling a ship upgrade doesn't increase the inventory of that item at the planet or base. Filed as #1222 . Note that this bug is present on the master branch as well. ~Should be fixed in the latest commit~ Not fixed
- At one point, near Serenity, most of the screen turned white when I switched to views 5 or 6
- Hit a failed assertion with a specific savegame. The assertion was that the last item in the base/planet inventory was "Basic Repair and Refuel." It wasn't, as this item was getting deleted by the code that removes …
> Migrate More General-Section Config Settings (and several smaller sections)

- engine/src/components/readme.rst
> Create readme.rst for LibComponents

- engine/src/cmd/basecomputer.cpp
- engine/src/components/components_manager.cpp
- engine/src/components/components_manager.h
- engine/src/main.cpp
- libraries/cmd/carrier.cpp
- libraries/cmd/carrier.h
- libraries/gfx_generic/cockpit_generic.cpp
- libraries/root_generic/savegame.cpp
- libraries/root_generic/savegame.h
- libraries/root_generic/universe_util_generic.cpp
closes #1286 
closes: #1281 [de6d8fb](https://github.com/vegastrike/Vega-Strike-Engine-Source/pull/1289/commits/de6d8fb8b606a639a9c40240782e0eb1fb650ee0)
Code Changes:
Issues:
- I've removed the variable pricing of repair. I can see it either way - it's expensive to buy here so the parts to repair are expensive too or it's mostly off the shelf parts and work and that's the same. My choice was simpler.
> Fix bug 1286

- engine/src/python/init.cpp
- engine/src/universe.cpp
- libraries/cmd/role_bitmask.cpp
- libraries/root_generic/galaxy_utils.cpp
- libraries/root_generic/options.cpp
- libraries/root_generic/options.h
- libraries/root_generic/vsfilesystem.cpp
Code Changes:
- Closes #1188 
- Nothing new that I'm aware of
Purpose:
- What is this pull request trying to do? Convert another section of settings to the new `configuration()....` way of doing things, namely the `data` section in this case.
> Convert `data` settings section

- engine/src/cmd/ai/firekeyboard.cpp
- engine/src/gamemenu.cpp
- engine/src/main.cpp
- libraries/root_generic/galaxy_gen.cpp
- libraries/root_generic/galaxy_utils.cpp
- libraries/root_generic/options.cpp
- libraries/root_generic/options.h
- libraries/root_generic/vsfilesystem.cpp
- vcpkg.json
Code Changes:
- Closes #1192 
- Nothing new that I'm aware of
Purpose:
- What is this pull request trying to do? Convert the `galaxy` and `network` settings section to the new `configuration()....` mechanism
> Convert galaxy settings

- engine/src/cmd/beam.cpp
- engine/src/cmd/unit_physics.h
- engine/src/configuration/tests/configuration_tests.cpp
- engine/src/gfx/cockpit.cpp
- engine/src/star_system.cpp
- engine/src/star_system_jump.cpp
- engine/src/universe.cpp
- libraries/cmd/armed.cpp
- libraries/cmd/audible.cpp
- libraries/cmd/movable.cpp
- libraries/cmd/unit_generic.cpp
Code Changes:
- Fixes #1164 
- Still reads mouse axes, button assignments, and enabled or disabled state from vegastrike.config
Purpose:
- What is this pull request trying to do? Fix #1164 
> Fix mouse movement

- script/bootstrap
- Fix CodeQL and local builders using `script/bootstrap` to configure the system
Code Changes:
Issues:
Purpose:
> Bug Fix: Add SDL2-image to the bootstrap

- libraries/gfx_generic/cockpit_generic.cpp
Fixes: #1113 
**Code Changes:**
**Tests Done**
Given the limited changes here, I tested flight in and out of jump points and actual jumps but nothing else.
**Issues:**
- None identified
> This tweak fixes the constantly toggling jump light.
